name: Auto-add proposals to project board

on:
  pull_request:
    types: [opened, labeled]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    if: >-
      contains(github.event.pull_request.labels.*.name, 'rfc') ||
      contains(github.event.pull_request.labels.*.name, 'feature-request') ||
      contains(github.event.pull_request.labels.*.name, 'design-doc')
    steps:
      - uses: actions/add-to-project@v1
        with:
          project-url: https://github.com/users/filvecchiato/projects/3
          github-token: ${{ secrets.PROJECT_PAT }}
